# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies (skip scripts to avoid lock mismatch)
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build the project
RUN npm run build

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
